### ISSUE TITLE
`xtal2png` without arguments throws `ValueError`

### ISSUE THREAD

**Issue by PeterKraus** [sparks-baird/xtal2png#145]
When I execute `xtal2png` without any command line arguments, I get a `ValueError`:
```
(xtal2png) kraus@dorje:~::xtal2png 
Traceback (most recent call last):
  File "/home/kraus/Applications/miniconda3/envs/xtal2png/bin/xtal2png", line 10, in <module>
    sys.exit(run())
  File "/home/kraus/Applications/miniconda3/envs/xtal2png/lib/python3.10/site-packages/xtal2png/core.py", line 1141, in run
    main(sys.argv[1:])
  File "/home/kraus/Applications/miniconda3/envs/xtal2png/lib/python3.10/site-packages/xtal2png/core.py", line 1112, in main
    raise ValueError("Specify at least one of --encode or --decode")
ValueError: Specify at least one of --encode or --decode
```
It would be much cleaner to print the `usage` message, or a different prompt telling the user what to do, rather than crashing on the user.

**Comment by kjappelbaum** [comment]
@sgbaird This would also be fixed by using click. If you agree, I can give it a shot tonight/tomorrow morning (Swiss time)

**Comment by sgbaird** [comment]
@kjappelbaum sounds great!
